Module6 task1
htmlacademy-php1/212049-readme-13 pull request #12
Opened 2021-08-22 23:29 UTC by YuriyMarks

2021-08-23 01:02 UTC, dshemin requested changes

2021-08-23 01:02 UTC, dshemin commented on index.php
> +$post_limit = ($type_id == 9) ? 'LIMIT 9' : 'LIMIT 6';
Почему такое условие?

2021-08-23 01:02 UTC, dshemin commented on index.php
> +if ($type_id == 0 or $type_id == 9) {
Очень хрупко. Если мы добавим или удалим тип - перестанет работать. Надо проверять, существует ли переданный тип в БД.

2021-08-23 01:02 UTC, dshemin commented on post.php
> +$con = mysqli_connect('localhost', 'root', '', 'readme');
Код соединения с БД у нас повторяется. Можно вынести в функцию и переиспользовать.

2021-08-23 01:02 UTC, dshemin commented on templates/main.php
> +                    <?php if($type_id == 9): ?>
А если у нас появится тип с таким ID?

2021-08-23 01:02 UTC, dshemin commented on index.php
> +if ($type_id == 0 or $type_id == 9) {
Не советую использовать `or` или `and`. Только `||` или  `&&`. А тем более смешивать оба подхода.

2021-08-23 01:02 UTC, dshemin commented on index.php
> +if ($type_id != 0 && $type_id != 9) {
По хорошему - это можно поместить просто в ветку `else`.

2021-08-23 01:02 UTC, dshemin commented on index.php
> +$type_id = isset($_GET['type_id']) ? (int) $_GET['type_id'] : '';
Если у нас что-то имеет должно быть числом, оно должно быть числом всегда. Тут `$type_id`, в зависимости от входных данных, будет либо числом, либо строкой - не надо так делать. Если хочется показать что в переменной ничего нет нужного, лучше подобрать валидное значение того же типа или использовать `null`.

2021-08-23 01:02 UTC, dshemin commented on index.php
> +if ($type_id == 0 or $type_id == 9) {
Используйте только строгие сравнения `===` или `!==`.

2021-08-23 01:02 UTC, dshemin commented on index.php
> +if ($type_id != 0 && $type_id != 9) {
Используйте только строгие сравнения `===` или `!==`.

2021-08-23 01:02 UTC, dshemin commented on templates/main.php
> +                    <?php if($type_id == 9): ?>
Используйте только строгие сравнения `===` или `!==`.

2021-08-23 01:02 UTC, dshemin commented on templates/main.php
> +                            <?php if($type_id == $type['id']): ?>
Используйте только строгие сравнения `===` или `!==`.

2021-08-25 09:53 UTC, b1rdex requested changes

2021-08-25 09:53 UTC, b1rdex commented on templates/post-link.php
> +    <a class="post-link__external" href="http://<?=$post['link'];?>" title="Перейти по ссылке">
xss

2021-08-25 09:53 UTC, b1rdex commented on templates/post-link.php
> +          <h3><?=$post['title'];?></h3>
xss

2021-08-25 09:53 UTC, b1rdex commented on templates/post-main.php
> +    <h1 class="page__title page__title--publication"><?=$post['title']?></h1>
xss

2021-08-25 09:53 UTC, b1rdex commented on templates/post-main.php
> +      <div class="post-details__wrapper post-<?=$post['class_name']?>">
xss

2021-08-25 09:53 UTC, b1rdex commented on templates/post-main.php
> +                <span><?=$post['author']?></span>
xss

2021-08-25 09:53 UTC, b1rdex commented on templates/post-quote.php
> +        <?=$post['content'];?>
xss

2021-08-25 09:53 UTC, b1rdex commented on templates/post-quote.php
> +      <cite><?=$post['login'];?></cite>
xss

2021-08-25 09:53 UTC, b1rdex commented on templates/post-text.php
> +      <?=$post['content'];?>
xss

2021-08-25 09:53 UTC, b1rdex commented on templates/post-video.php
> +  <?=embed_youtube_video($youtube_url); ?>
Кажется тут должно быть что-то из $post[]

2021-08-25 09:53 UTC, b1rdex commented on post.php
> +	header(' ', true, 404);
http_response_code()

2021-08-25 09:53 UTC, b1rdex commented on post.php
> +$post = mysqli_fetch_assoc($res);
Всё что выделил выносим в функцию get_post(int $postId) в functions.php

2021-08-25 09:53 UTC, b1rdex commented on post.php
> +	header(' ', true, 404);
http_response_code

2021-08-25 09:53 UTC, b1rdex commented on index.php
> +$cardsOnPageAll = (isset($_GET['cardsOnPageAll'])) ? true : false;
```suggestion
$cardsOnPageAll = isset($_GET['cardsOnPageAll']);
```

2021-08-25 09:53 UTC, b1rdex commented on index.php
>  function truncateText($text, $maxLength = 300) {
Все функции выносим в functions.php. По критериям для защиты у каждой функции должен быть phpDoc комментарий. Также, я рекомендую всем аргументам функций поставить тип и добавить тип возвращаемого значения.

2021-08-25 09:53 UTC, b1rdex commented on index.php
>  $query_types = 'SELECT * FROM content_types';
Запрос на выбор типов постов выносим в отдельную функцию get_post_types() в functions.php

2021-08-25 09:53 UTC, b1rdex commented on index.php
> +$query_posts_def = 'SELECT users.login AS author, content_types.*, posts.*, users.avatar,' .
Получение постов выносим в отдельную функцию get_posts(?int $typeId)

2021-08-25 09:53 UTC, b1rdex commented on index.php
> +$query_posts_def = 'SELECT users.login AS author, content_types.*, posts.*, users.avatar,' .
Логику по limit 6/9 делаем внутри функции, в зависимости от $typeId

2021-08-26 05:47 UTC, b1rdex requested changes

2021-08-26 05:47 UTC, b1rdex commented on post.php
> +	header(' ', true, http_response_code(404));
```suggestion
	http_response_code(404);
```

2021-08-26 05:47 UTC, b1rdex commented on post.php
> +$post = mysqli_fetch_assoc($res);
Актуально, почему не вынес в функцию? :)

2021-08-26 05:47 UTC, b1rdex commented on post.php
> +	header(' ', true, http_response_code(404));
```suggestion
	http_response_code(404);
```

2021-08-26 05:47 UTC, b1rdex commented on templates/post-video.php
> +  <?=embed_youtube_video($youtube_url); ?>
Актуально, не исправил

2021-08-26 05:47 UTC, b1rdex commented on templates/post-text.php
> +      <?=$post['content'];?>
Актуально, не исправил

2021-08-26 05:47 UTC, b1rdex commented on templates/post-quote.php
> +        <?=$post['content'];?>
Актуально, не исправил

2021-08-26 05:47 UTC, b1rdex commented on functions.php
> +function getPosts($type_id, string $cardsOnPageAll, object $con): array {
```suggestion
function getPosts(?int $type_id, bool $cardsOnPageAll, object $con): array {
```
?int это int|null
ну а cardsOnPageAll не понял – почему строка?

2021-08-26 13:10 UTC, merged