Module6 task2
htmlacademy-php1/212049-readme-13 pull request #13
Opened 2021-09-01 19:44 UTC by YuriyMarks

2021-09-04 03:31 UTC, b1rdex requested changes

2021-09-04 03:31 UTC, b1rdex commented on add.php
> +$formType = isset($_POST['content-type']) ? trim(key($_POST['content-type']), '\'') : 'photo';
А почему не сделал input[type=hidden] с value = типом поста? Было бы проще кмк, чем работать с ключём массива

Ну и в целом, можно вообще отказаться от передачи этого в $post, ведь у тебя уже оно выставляется в $get. Просто у формы нужно убрать action, чтобы отправлялось в текущий url

2021-09-04 03:31 UTC, b1rdex commented on functions.php
> +        if (in_array($key, $required) && empty($value)) {
У тебя тут неправильная логика – в $required ты ищешь только то, что было отправлено в $post. А если поле не отправили, то валидация это пропустит, хоть поле и обязательное.

2021-09-04 03:31 UTC, b1rdex commented on add.php
> +            if (!$error = validateImage() && !$errors) {
Почему бы не передавать $_FILES['userpic-file-photo'] аргументом функции? Это будет намного лучше, чем работать с глобальным состоянием из функции

2021-09-04 03:31 UTC, b1rdex commented on add.php
> +    $errors = validateForm($rules, $required);
По-хорошему, нужно передавать $_POST в функцию аргументом и не работать с глобальным состоянием

2021-09-04 03:31 UTC, b1rdex commented on add.php
> +            $error = downloadImageFile();
Здесь тоже ссылку аргументом

2021-09-04 03:31 UTC, b1rdex commented on functions.php
> +    }
Не хватает проверки на ошибку выполнения запроса

2021-09-04 03:31 UTC, b1rdex commented on functions.php
> +    list(,$title, $content, $quote_author) = array_values($_POST);
Лучше передавать $post явно

2021-09-04 03:31 UTC, b1rdex commented on functions.php
> +function insertPostToDatabase($con, $postType, $filePath): void {
передавай $userId аргументом

2021-09-04 03:31 UTC, b1rdex commented on functions.php
> +    $stmt = mysqli_prepare($con, $postQuery);
Тут может быть ошибка, что $postQuery не объявлена

2021-09-04 03:31 UTC, b1rdex commented on functions.php
> +    if(@!mysqli_stmt_execute($stmt)) {
Собаку убираем

2021-09-04 03:31 UTC, b1rdex commented on functions.php
> +    } else {
else не нужен, т.к. в if всегда заканчивается выполнение через die

2021-09-04 03:31 UTC, b1rdex commented on functions.php
> +        //header('Location: post.php?post_id=' . $postId, true, 303);
Почему закоментировано? Код должен быть 302 вместо 303

2021-09-04 03:31 UTC, b1rdex commented on functions.php
> +    global $filePath;
Это нельзя использовать

2021-09-04 03:31 UTC, b1rdex commented on functions.php
> +    if(@!$fileContent = file_get_contents($link)) {
Собаку убираем

2021-09-04 03:31 UTC, b1rdex commented on functions.php
> +    global $filePath;
Это нельзя использовать

2021-09-04 21:53 UTC, YuriyMarks commented on functions.php
> +        if (in_array($key, $required) && empty($value)) {
не понял

2021-09-05 09:20 UTC, b1rdex requested changes

2021-09-05 09:20 UTC, b1rdex commented on functions.php
> +    }
Актуально

2021-09-05 09:20 UTC, b1rdex commented on functions.php
> +    $stmt = mysqli_prepare($con, $postQuery);
Актуально

2021-09-05 09:20 UTC, b1rdex commented on functions.php
> +    if(@!mysqli_stmt_execute($stmt)) {
Актуально

2021-09-05 09:20 UTC, b1rdex commented on functions.php
> +    header('Location: post.php?post_id=' . $postId, true, 302);
Нужно ещё добавить exit/die после header(), чтобы не выполнять страницу дальше

2021-09-05 09:20 UTC, b1rdex commented on functions.php
> +            $filterRules[$key] = 'FILTER_DEFAULT';
Это не строка, а константа. Нужно убрать кавычки

2021-09-05 09:20 UTC, b1rdex commented on functions.php
> +        if (in_array($key, $required) && empty($value)) {
Вынеси просто проверку в отдельный цикл:
```php
foreach ($required as $key) {
	if empty($post[$key]) { ... }
}
foreach ($post as $key => $value) {
	// остальные проверки
}
```

2021-09-06 12:38 UTC, b1rdex requested changes

2021-09-06 12:38 UTC, b1rdex commented on functions.php
> +    }
Проверки на ошибку так и не вижу

2021-09-06 12:38 UTC, b1rdex commented on functions.php
> +    $stmt = mysqli_prepare($con, $postQuery);
Проблема актуальна

2021-09-06 13:12 UTC, merged